version: "3.3"

services:
    bulk-email-processor:
        image: bulk-email-processor
        ports:
            - "3030:3030"
        environment:
            - BEP_SERVER_URL=${BEP_SERVER_URL}
            - BEP_ENV=${BEP_ENV}
            - BEP_SESSION_SECRET=${BEP_SESSION_SECRET}
            - BEP_MAKE_MIGRATION=${BEP_MAKE_MIGRATION}

            - BEP_MONGODB_URL=${BEP_MONGODB_URL}

            - BEP_MAILTRAP_CREDENTIAL=${BEP_MAILTRAP_CREDENTIAL}

            - CLOUDAMQP_URL=${CLOUDAMQP_URL}
            - PORT=${PORT}


